apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: roboshop
  labels:
    component: payment
    project: roboshop
    tier: app
spec:
  replicas: 1
  selector:
    matchLabels:
      component: payment
      project: roboshop
      tier: app
  template:
    metadata:
      labels:
        component: payment
        project: roboshop
        tier: app
    spec:
      containers:
      - name: payment
        image: joindevops/payment:v1
        envFrom:
        - configMapRef:
            name: payment
        - secretRef:
            name: payment
        ports:
        - containerPort: 8080
